### ISSUE TITLE
package.json does not list devDependencies

### ISSUE THREAD

**Issue by LynnKirby** [commonmark/commonmark.js#142]
The packages used during development should be included in `package.json`. Many are listed in the readme or installed via make. The project should conform to the standard development route of using a single `npm install` to setup the environment.

**Comment by jgm** [comment]
I don't know much about npm packaging, so feel free to educate me.  But
I don't want to require the benchmark dependencies (e.g. showdown) as
part of "dependencies," since that would mean that anyone installing
commonmark.js will have to install all of those dependencies too.

Benchmarks are useful for developers, but end-users shouldn't have
to install the benchmark dependencies.  Same goes for programs
used for linting.

**Comment by LynnKirby** [comment]
That's what [`devDependencies`](https://github.com/npm/npm/blob/v6.1.0/doc/files/package.json.md#devdependencies) are for. They don't get installed unless you `npm install` from the package root (e.g. as a developer working on it) or if the consumer of the package opts in with a CLI flag.
