### ISSUE TITLE
Empty list item as setext header underline

### ISSUE THREAD

**Issue by davidmehren** [commonmark/commonmark.js#222]
If I input a [list like this](https://spec.commonmark.org/dingus/?text=-%20something%0A%20%20-%20) into dingus :
```
- something
  - 
```
the output is
```
<ul>
<li>
<h2>something</h2>
</li>
</ul>
```
That looks like the second line gets interpreted as a setext heading underline. The spec says:
> If a line containing a single `-` can be interpreted as an empty list items, it should be interpreted this way and not as a setext heading underline.

Isn't the second line an empty list item and commonmark.js therefore wrong? The quoted sentence seems to have been added to the spec after exactly this situation was brought up: https://github.com/commonmark/commonmark-spec/issues/95

**Comment by jgm** [comment]
I have no memory of this; it was a long time ago. But it does look as if the spec was changed, but without adding an example for this, and the reference implementations don't seem to have been changed accordingly.

We should add this as an example to the spec, and fix the parsers.
(cmark too)

**Comment by jgm** [comment]
Ah wait!  I understand now.  From the spec:

https://spec.commonmark.org/0.30/#example-285

An empty list item can't interrupt a paragraph.

Given this (which was probably added after commonmark/commonmark-spec#95) we can probably remove the text added in commonmark/commonmark-spec#95.

**Comment by DougInAMug** [comment]
Thanks for posting David, and for responding @jgm 

I noticed this behavior due to writing markdown in hedgedoc (commonmark), where I opened [this issue](https://github.com/hedgedoc/hedgedoc/issues/1441#issuecomment-878598241). David did some digging, and ended up here.

My group copies meeting notes—often with empty, indented hyphen-style points—made in hedgedoc to grav, which uses parsedown, and renders the empty, indented bullet 'the way I expect'. https://parsedown.org/demo

I've had a look at the spec links you added, thanks. Reading [Gruber's page](https://daringfireball.net/projects/markdown/basics) helped me understand what setext is. Still, I don't understand why

```
- This is interpreted as a setext h2 
    -
```

```
- And this isn't
-
```

Is this decision set in stone? If not, how might I constructively go about changing it?

**Comment by jgm** [comment]
In the first case the content
```
This is interpreted as a setext h2
  -
```
is put in a list item. Since this content gets read as a setext header, that's what we get.  In the second case the `-` is not part of the preceding list item, because it isn't indented enough.

I would suggest that for your purposes, you simply put a blank line before the first list item, so that it doesn't interrupt a paragraph:
```
1.  New business

   -
   -

2. Old business

   -
   -
```

**Comment by jgm** [comment]
Alternatively you could use `x` or some visible placeholder (if you want the tight list).

Is it set in stone?  No, nothing is set in stone yet.  And I think it would have been very reasonable to require at least two `--`s for a setext header.  But that would be a backwards-incompatible change.  (I think I actually did a study of a corpus of markdown documents when this came up before, and a significant number of setext headers used one `-` for the underline...)

**Comment by jgm** [comment]
If you want to raise the issue for discussion, talk.commonmark.org is the place to do that.
(But first look for prior relevant discussions.)

**Comment by jgm** [comment]
By the way, the commit that forbids empty list items from interrupting paragraphs is
```
commit 02ae86a2c15bc469004d86a68760014dfaf94e33
Author: John MacFarlane
Date:   Wed Jul 13 11:40:12 2016 -0700

    Empty list items cannot interrupt a paragraph.
    
    This removes an ambiguity between setext headers and
    lists in cases like
    
        foo
        -
```
There's no reference, but this may have been motivated by a discussion on the forum.
It's odd that I didn't notice the clash with commonmark/commonmark-spec#95 at the time.  Wish I had a better memory.  A case could be made for reinstating commonmark/commonmark-spec#95 and undoing this, but I'm hesitant to do that without a better grasp of the issue that motivated this change.

Perhaps an issue should be opened at commonmark/commonmark-spec to resolve this conflict in a rational way...

**Comment by DougInAMug** [comment]
Thank you for the detailed answer! Appreciate that.

I still don't quite get quite get it :sweat_smile: In both of my examples, the first lines begin with hyphens (meaning they aren't paragraphs, right?), whereas in your example and the final reference, they don't... anyway, you've spent way more time with this than I, so I will just trust you that this behavior is conformant, and assume personal ignorance.

Thanks for the empty line suggestion, and the suggestions on how to go forward :+1:

**Comment by jgm** [comment]
The *content* of the list item begins with a paragraph. So the question is whether that paragraph can be interrupted by a new list item, without an intervening blank line.

**Comment by DougInAMug** [comment]
After reading quite a lot of the Commonmark Spec, and sleeping on it, I finally understand what you are saying! I think it took so long because I _never_ use setext headings (indeed, don't know anyone personally).

I think it is quite unfortunate that there will probably always be tension between setext headings and empty, hyphenated list items then :( I guess I'll just try to avoid empty points as best possible (which is not optimal, for my use case of a shared, regular meeting pad, where the same sections are reused each week) 

Seems like Pandora's Box has been opened, I see no way to change it with out breaking changes. However, I'm willing to bet there are _very few_ people who use bulleted, h2 setext headers :smile: Also, I think most people prefer hyphens for lists, because it is only one keystroke on the English keyboard.

As such, I do believe there is a strong, pragmatic argument for keeping https://spec.commonmark.org/0.30/#setext-headings as it is, and not interpreting `foo` in

```
- foo
    -
```

as an h2.

Should I summarize this in a new spec issue & link? Cheers.

**Comment by DougInAMug** [comment]
**'Workaround'**

```
- foo
    *
```

**Comment by jgm** [comment]
> I'm willing to bet there are very few people who use bulleted, h2 setext headers

Undoubtedly true!  However, commonmark has a Principle of Uniformity, which says that block-level content inside list items should be parsed the same way as it would be outside, and this means that headings inside list items are allowed.

If you want to open an issue at commonmark-spec, that would be welcome.
