### ISSUE TITLE
[request] output to plain markdown

### ISSUE THREAD

**Issue by braco** [commonmark/commonmark.js#251]
It would be really handy to have the option to output to plain/simple/HTML-free Markdown.

ie, convert from CommonMark to Markdown.

> -t,--to FORMAT  Specify output format (xml, html, ast)

to

> -t,--to FORMAT  Specify output format (xml, html, ast, **md**)

It would help fix problems between software that outputs CommonMark and parsers that only consume plain Markdown, like this issue:

https://github.com/Mermade/widdershins/issues/294

**Comment by jgm** [comment]
Is this just requesting the same thing as #83? (In that case it should be closed as a duplicate.)

**Comment by braco** [comment]
Don't think so, this request is to write out to Markdown, and remove CommonMark features like HTML

**Comment by jgm** [comment]
This library doesn't even yet have a module to write out commonmark.
Since it's a reference implementation for commonmark, adding one would not be out of scope.
But adding a module that outputs something other than commonmark would be.

By the way, I don't understand any of this.  Inline HTML is a basic Markdown feature.  See the original syntax description by John Gruber.  It is supported by every Markdown implementation I know of.

If we ever do add a commonmark renderer, it will of course be possible to modify the renderer so that it suppresses any raw HTML output.

Closing this.
